name: Quality check

on: [push]

jobs:
  quick-check:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v4

      - name: Setup required Node.JS version
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'npm'

      - name: Dependency installation
        run: npm install

      - name: Run tests
        run: npm test
