name: Quality check

on: [push]

jobs:
  quick-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v3

      - name: Setup required Node.JS version
        # node-version-file will support package.json file
        # once they publish it as a stable release please uncomment the below line
        # uses: actions/setup-node@v3
        uses: actions/setup-node@348e00800850ca70958af8888ebdb3cce7cbcddc
        with:
          node-version-file: 'package.json'

      - name: Dependency installation
        run: npm install

      - name: Run tests
        run: npm test
