name: Quality check

on: [push]

jobs:
  quick-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v2

      - name: Setup required Node.JS version
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Dependency installation
        run: npm install

      - name: Run tests
        run: npm test
